In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.shape

(891, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
# mode inputation

In [14]:
df.drop('Cabin', axis=1, inplace=True)

In [15]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [19]:
HOW TO CHECK MISSING VALUES
df.isnull().sum()

This tells how many missing values each column has.

DIFFERENT WAYS TO HANDLE MISSING VALUES
1. Fill with Mean (MOST COMMON)

Used for:

✅ Numerical continuous data

Examples:

Age
Salary
Height
Weight
Code
df['Age'] = df['Age'].fillna(df['Age'].mean())
Why Mean?

Because it keeps average distribution balanced.

When NOT to use Mean

❌ If data has many outliers.

Example:

10, 12, 15, 1000

Mean becomes very large.

2. Fill with Median

Used when:

✅ Numerical data has outliers

Examples:

Income
House price
Fare
Code
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
Why Median?

Median is not affected by outliers.

Example

Data:

10, 12, 15, 1000

Mean = huge

Median = 13.5 (better)

3. Fill with Mode

Used for:

✅ Categorical/Text data

Examples:

Gender
City
Embarked
Code
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
Why Mode?

Mode = most frequent value.

Example
Gender
Male
Female
Male
NaN

Fill with:

Male

because it appears most.

4. Drop Rows

Used when:

✅ Very few missing rows

Code
df.dropna(inplace=True)
Why?

If only few rows missing, removing them is okay.

When NOT to Use

❌ If dataset becomes too small.

5. Drop Columns

Used when:

✅ Column has TOO MANY missing values.

Example:

Cabin
NaN
NaN
NaN
Code
df.drop('Cabin', axis=1, inplace=True)
Why?

Column has little useful information.

TITANIC DATASET EXAMPLE
Column	       Best Method	    Why
Age	           Mean	            Numerical continuous
Fare	       Median	        Possible outliers
Embarked	   Mode	            Categorical
Cabin	       Drop column	    Too many missing values
    
HOW TO DECIDE WHAT TO USE
Rule of Thumb
    
Data Type	                                        Method
Numerical normal data	        -->                  Mean
Numerical with outliers	        -->                  Median
Categorical/Text	            -->                  Mode
Too many missing rows	        -->                  Drop rows
Too many missing column values	-->                  Drop column
    
IMPORTANT VIVA QUESTION
Why not always drop missing values?

Answer:
Dropping data may reduce dataset size and important information may be lost.

Another Important Viva
Difference between Mean and Median?
Mean	                   Median
Average value	           Middle value
Affected by outliers	   Not affected
BEST ANSWER FOR YOUR TITANIC ASSIGNMENT

You can say:

Age column missing values are handled using mean because Age is numerical continuous data.

Cabin column can be dropped because it contains many missing values.

Embarked missing values can be handled using mode because it is categorical data.


    df['Fare'] = df['Fare'].fillna(df['Fare'].median())
this just a example

In [20]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [21]:
df['Sex'] = df['Sex'].map({'male':0, 'female':1})

In [22]:
# One Hot Encoding for multi-category column
df = pd.get_dummies(df, columns=['Embarked'])

In [23]:
# Display final dataset
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,False,True

In [24]:
df['Fare'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,0.014151,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,0.139136,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,0.015469,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,0.103644,False,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,0.015713,False,False,True